### ISSUE TITLE
JetHub H1. Сообщения wlan засоряет лог

### ISSUE THREAD

**Issue by Funcy-dcm** [jethome-ru/build-armbian-old#3]
Каждую минуту в лог пишется сообщения wlan, при этом wlan не используется:

Feb 15 22:52:51 localhost kernel: [  426.024940] RTW: cfg80211_rtw_scan(wlan0)
Feb 15 22:52:51 localhost kernel: [  426.026243] RTW: [HW_VAR_CHECK_TXBUF] Empty in 0 ms
Feb 15 22:52:51 localhost kernel: [  426.026325] RTW: wlan0 sleep m0=0x00000002, ori reg_0x4d4=0x00000000
Feb 15 22:52:55 localhost kernel: [  430.067688] RTW: wlan0 wakeup m0=0x00000002, ori reg_0x4d4=0x00000002
Feb 15 22:52:55 localhost kernel: [  430.067750] RTW: survey done event(9) band:0 for wlan0
Feb 15 22:52:55 localhost kernel: [  430.067862] RTW: rtw_indicate_scan_done(wlan0)

**Comment by adeepn** [comment]
Исправлено в новых билдах armbian http://update.jethome.ru/armbian/release/
